server:
  ip: 121.40.234.7
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.234.7:3306/mall?serverTimezone=GMT%2b8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
#    path: /home/files/
    path: D:/java/project/网上书城/files/
