server:
  ip: 121.40.234.7
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.234.7:3306/mall?serverTimezone=GMT%2b8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
#    path: /home/files/
    path: D:/java/project/网上书城/files/

#支付宝配置
alipay:
  #appid
  appId: 2021000122635036
  #应用私钥
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCHeV08sq2x9P86WhuFzyUBbjEo6Wz4QumErrjKkGKvQiibs9YLtmJBpM9UVTJmIqG61dJ6bV2evb88XOzaWjaO+51D6Js+0tgx+gtKWgcTISnxNWGoSE7zdknT1FQXv4wUAwYm1gvxoJxuG+yyarbhhRHTXVo6ATaUgqXP9Qote1/kCJJJTDi/hY75yfrlkoirWWELBdNOKtrD0idWJajl9k1+uKNpPDiLyaetizOwa5s8JA64LBYZia8uq13SvAQ6HVfZXEShssf7kzbYecTkWruvqtBl3EBRBIQFqTeszACgq7cP4W/11/5qXoHe9x61TxsTZwiCj5i4XgM73zCfAgMBAAECggEAHvjRJxpWeZPgce+90RatiCkwFgFfx1ZM2uezGaRu21CNxiMUMXNN/WH3gHlF33HVdciCqTitqagJu3wnLjhntsKxjp/0NiWwBaT7xdDVQztWwm2I2RdG7YRClqo5W4CQPtb+JgzTiDdG7Cl4MMYS73YjwCXchdxXJRbFX8jOvdzbNV8t+NJZ8Vzf+UaHzZ+mmtVwq7GlfEAZ5QTVTnGfaWP/2/b1e/5xDuXOIqOlm0pT87JSdPWOfnm7VONUgWejcUMFAsAfIQ7DHnNSokE8qHGtvlgvz/VWMR410IOeXul32NJtsE9DFdYz8GFDZe2gBULsMOZHFoj41V6GIn34+QKBgQDhfChhqiy/VddDf7ziQ4RHrl1WKy1iEghEVY4roOuMENM+G2N5/Ds7V5BNetZf2M88Fk64I5VyUA5UOE0QpKQYpx94Yv/e9ZQeRdIEjsoO/bNA3YJOrqvO4O8mCUmiekap/hea2dL92Ctqs8D0Ra7nCYMoKgVjN+FD1XEEuofnUwKBgQCZzs/8ixe0QxHMUehPA+ZNhWYNfHwbOcAIbTpbtafF8yrLulrcYryGQyjYvyhBrBxkpilu2tiRKae/hSl/uZ2R2222oXMbRtXst78Gawpe2mXVACevE5aDMxRX1u4zraVCXbeW0zKPEzZp8fOnRpo21fdJ1NGlEqNFR/MItJAkBQKBgDkqR/aStSuA8MUtEk7uvQ+LNiCNa8EMP0pLwnJvJqho75U0TmDzwHSH+46ZENZV2hwqr6RhaRcFEszpRShuBSg23nSf7Kyy5+1Q2DDNno50ZUiRn+Kgx+/3+MlU23U0uMuKHqPki2hNsJwpnEaRkAkE0VqSZLFFzndrGm8Pdzr/AoGAI6zNnzUf9WbNHQguiw1LgNWdOymRm7sEaK/1Jkp3NLnXRlPeOVoJglbXhZapHrpuB4Zm+9h0/Q6dYxXe70o9WxR7WS4PhdcjTXm9LB7t09xyXDph+gDgG2RgppMqwv/W4hLcv3YTNw5sw5wkOLtuj6OHbS+YxOISzsIGhBFlkYUCgYEA3+8hzFCR8NUCOeUd4MNwNJei96qS01+7ySiyzbrHPV/WfTMKLcsu2D//tFdQtEGBeWI/jV8XL5BngR1clBKNTeYmrSbYAzuuBWtrbyg1n23IOYXfckPn5+xEdjAey8VyLCc6UqEdgWC3gHHthk3Dx56xFsJhMQr2NN94zI6o6po=
  #支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnDbOv0RpIwt3q0316AV0LWE7Jm4UU+2JYTB0Qw1i3fHYO45sSmZbzBhRqymFLkihV4tFQBNSWfdD17FOWGE8OmhY4nT5eiuechqruEY7eD2AuwPUNb8R/3Bijbn0XOitvpmAU6fKLaQxtSBY5sU0SUZ+epSQvbCncKphnqtcUj2MH7KuVOqpdEP60kjFcGmLc2Nnou4EvLBP4j7ba4XDt8SFzC3/cItbwwLqa92y0dGhQhBG0JNuMYr0u6rr6wt+DAxaSlRGjHdbS+GpSVwabM1ihYn9Ty/EjlEaHaMhZ7zeDe7F67R2shKNIiqWinyoKN3xMhLbDinu7KychHqJXwIDAQAB
  #内网穿透域名
  notifyUrl: http://jxdg4u.natappfree.cc/alipay/notify
